spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
mybatis:
  type-aliases-package: com.whx.bus.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
    console: "%d - %msg%n"
